name: "deit_small_patch16_224"
pretrained: true
num_classes: 1000
input_size: 224
base_lr: 0.0001
weight_decay: 0.05
epochs: 30

dataset:
  name: imagenet100
  data_dir: /home/stella/data/imagenet100
  # data_dir: C:/Users/이현수/Downloads/archive
  num_workers: 8