name: "mobilenet_v2"
num_classes: 100
input_size: 224
pretrained: false
base_lr: 0.005
momentum: 0.9
weight_decay: 0.0001
epochs: 220
batch_size: 128
num_workers: 8
scheduler: "cosine"

dataset:
  name: "imagenet100"
  data_dir: "/home/stella/data/imagenet100"
  num_workers: 8
