# strategy:
#   method: "pdt"
#   start_epoch: 120
#   method: "PDT-Blackwell-Custom"
#   ema_decay: 0.95
#   lambda_h: 0.0005
#   hessian_iter: 10
#   k_horizon: 5
#   #그룹 선정 비율
#   group_selection_ratio: 0.9
#   #최종적으로 생존 채널 비율 
#   channel_keep_ratio: 0.9
#   min_survival_ratio: 0.3

strategy:
  method: "pdt"
  start_epoch: 50
  method: "PDT-Blackwell-Custom"
  ema_decay: 0.95
  lambda_h: 0.0005
  hessian_iter: 10
  k_horizon: 5
  #그룹 선정 비율
  group_selection_ratio: 0.9
  #최종적으로 생존 채널 비율 
  channel_keep_ratio: 0.9
  min_survival_ratio: 0.3