strategy:
  method: "pdt"
  pruner: "tpp"
  start_epoch: 50
  ema_decay: 0.95
  lambda_h: 0.0005
  hessian_iter: 10
  k_horizon: 25
  #그룹 선정 비율
  group_selection_ratio: 0.9
  #최종적으로 생존 채널 비율 
  pruning_ratio: 0.1
  min_survival_ratio: 0.3

